### ISSUE TITLE
make error during raremetal build from source

### ISSUE THREAD

**Issue by domaniqs** [statgen/raremetal#10]
Hi,
I'm getting the error while trying to compile raremetal from the main master repository, below is the command output:

[raremetal_make_log.txt](https://github.com/statgen/raremetal/files/2961861/raremetal_make_log.txt)

Could anyone please shed some light on the issue and what is causing it. I had no problems with building metal and from documentation on WIKI, it should be pretty straightforward to build RAREMETAL but it is not. 
Thank you

Maciej

**Comment by abought** [comment]
Greetings. We're sorry to hear you had problems compiling.

As a first step, I'd encourage you to try compiling from the `develop` branch instead- it includes a total rework of the build process.  See the README file on that branch for details.

In particular, this branch should do a much better job of compiling on other platforms (eg not just a specific version of ubuntu).
https://github.com/statgen/raremetal/tree/develop

Please let us know if the problems persist.

**Comment by domaniqs** [comment]
Many thanks for addressing my query!
However I still have problems, even using the developer version as advised:
-"cget install -f requirements.txt" returns command not found and I don't seem to have cget on my system installed or locate what package it is part of, in order to install it. Also there is no requirements.txt file, so even if I had cget, it wouldn't work.
-when I run: 
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cget/cget/cget.cmake -DBUILD_TESTS=1 ..`
it produces: 

> CMake Error: The source directory "/opt/optional_programs/raremetal" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

-even when I change the command to have correct path on my system to: 
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../otherLib/eigen-3.2.0/CMakeLists.txt -DBUILD_TESTS=1 ..
`
I'm getting the same error about missing CMakeLists.txt file.

Am I doing domething wrong or it is some misconfiguration of Makefile.inc or other file?

Maciej

**Comment by abought** [comment]
Thanks for following up. I'm a bit surprised that you say there is no requirements.txt file, as it is indeed part of the repo:
https://github.com/statgen/raremetal/blob/develop/requirements.txt

At the risk of asking a trivial question,  can you verify that you are checked out onto the develop branch? (`git status`,  or `git rev-parse HEAD`, which is a1e648edc98a1097e79f18ecf4f2ffd69542ba1b as of this writing)

See the [cget](https://github.com/pfultz2/cget#getting-cget) page for install instructions.


Your bug report did identify one possible issue that we are following up on, but it would only occur after the program had compiled.

**Comment by domaniqs** [comment]
well, I cloned:
[https://github.com/statgen/raremetal.git](url)
and after cloning it there is no requirements.txt in my cloned repository on my disk.
Thank you for the link to cget, now I have it installed.

**Comment by abought** [comment]
When you clone a fresh repository from the URL above, it *contains* the several branches, but at first download, it will default to being at the `master` branch. 

You would need to run `git checkout develop` to be on the develop branch.

(Apologies if you have already done this- our users come from a wide range of backgrounds, and as a result our instructions err on the side of being very detailed).

**Comment by domaniqs** [comment]
I have unsupported version of CMake:

> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.2 or higher is required.  You are running version 2.8.12.2

I'll fix this up, clone the right branch and try again, many thanks for your help

**Comment by abought** [comment]
Thanks for the info!

It may take us a bit of time to get to the error I mentioned (involving missing variants when loading data). I'll try to update you once we have a chance to investigate, in case it affects any analysis you will need to do.  Every bug report helps make sure that problems get on our radar (and fixed) as needed- thank you!

**Comment by abought** [comment]
Update: in the process of helping you, we found a small error in calculations that could affect output results. We have fixed that error, and created an official release [4.15.0](https://github.com/statgen/raremetal/releases/tag/v4.15.0).

Thanks!

**Comment by domaniqs** [comment]
Thank you for the update. I am in the process of solving issues with developers related to installation of new releases of CMake on CentOS, so it might take a bit :-)

**Comment by domaniqs** [comment]
OK, now I'm back to raremetal (had to delay things because of other arrangements).
While executing 

> cget install -f requirements.txt

I get this: 
`
[ 44%] Building CXX object CMakeFiles/savvy.dir/src/savvy/savvy.cpp.o
In file included from /var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/src/savvy/sav_reader.cpp:7:0:
/var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/include/savvy/sav_reader.hpp:20:34: fatal error: shrinkwrap/istream.hpp: No such file or directory
 #include <shrinkwrap/istream.hpp>
                                  ^
compilation terminated.
In file included from /var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/include/savvy/reader.hpp:11:0,
                 from /var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/src/savvy/reader.cpp:7:
/var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/include/savvy/sav_reader.hpp:20:34: fatal error: shrinkwrap/istream.hpp: No such file or directory
 #include <shrinkwrap/istream.hpp>
                                  ^
compilation terminated.
In file included from /var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/src/savvy/vcf_reader.cpp:7:0:
/var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/savvy-019a1ddaa9ec588f807f234f68787862f94ea057/include/savvy/vcf_reader.hpp:26:29: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
                             ^
compilation terminated.
gmake[2]: *** [CMakeFiles/savvy.dir/src/savvy/reader.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/savvy.dir/src/savvy/sav_reader.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/savvy.dir/src/savvy/vcf_reader.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/savvy.dir/all] Error 2
gmake: *** [all] Error 2
Command failed: ['/usr/local/bin/cmake', '--build', '/var/tmp/raremetal/raremetal-4.15.0/cget/cget/build/tmp-0f4c54df9a6546da982239d88ae5bdce/build', '--config', 'Release', '--', '-j', '20']
Failed to build package statgen/savvy
`

any Ideas what might be causing this.

**Comment by abought** [comment]
Thanks for the report. Just as a first question: are you using the newest version (official release 4.15.0, commit hash  dbd2cff ?)

**Comment by domaniqs** [comment]
I did not perform diff on it, just downloaded packed tar.gz version from the link you sent above.

**Comment by jonathonl** [comment]
I suspect you are using cmake v3.14.0. This version of cmake breaks things but will be fixed in cmake v3.14.1 when that is released (https://gitlab.kitware.com/cmake/cmake/issues/19079). In the meantime, you can use an earlier version. I know that this issue does not exist in 3.8.1 and earlier.

**Comment by domaniqs** [comment]
oooh, I didn't see that coming, since previously raremetal refused to compile because my cmake version was too old (the original one installed with Centos 7), OK I'll replace the cmake with older version and see how it goes. Thank you!

**Comment by domaniqs** [comment]
OK, it is compiling fine with cmake-3.13.4 (which I believe is the previous version).
Which files I should copy (or symlink) to my /usr/bin directory to let researchers use it (make install)?

**Comment by abought** [comment]
Relative to the project root, I would start with these two executables:

- `build/raremetalworker`
- `build/raremetal`

**Comment by domaniqs** [comment]
Thank you!
