### ISSUE TITLE
raremetal gene-based tests fail when using cov matrices output by rvtests

### ISSUE THREAD

**Issue by gjmzajac** [statgen/raremetal#12]
All data is from the tutorial.

This command for a Burden tests with cov matrices from rvtests produces no output for the burden test:

/net/wonderland/home/gzajac/raremetal-develop/build/raremetal --summaryFiles /net/wonderland/home/gzajac/raremetal_tutorial/rvtests.summaryfiles --covFiles /net/wonderland/home/gzajac/raremetal_tutorial/rvtests.covfiles --groupFile /net/wonderland/home/gzajac/raremetal_tutorial/group.file --burden --prefix /net/wonderland/home/gzajac/raremetal_tutorial/COMBINED.rvtests.QT1

See the output:
/net/wonderland/home/gzajac/raremetal_tutorial/COMBINED.rvtests.QT1.meta.burden.results

but when I replace the cov matrices from rvtests with the ones generated by raremetalworker,  it runs.

/net/wonderland/home/gzajac/raremetal-develop/build/raremetal --summaryFiles /net/wonderland/home/gzajac/raremetal_tutorial/rvtests.summaryfiles --covFiles /net/wonderland/home/gzajac/raremetal_tutorial/covfiles --groupFile /net/wonderland/home/gzajac/raremetal_tutorial/group.file --burden --prefix /net/wonderland/home/gzajac/raremetal_tutorial/COMBINED.rvt_sum_f.rwm_cov_f.QT1

See the output:
/net/wonderland/home/gzajac/raremetal_tutorial/COMBINED.rvt_sum_f.rwm_cov_f.QT1.meta.burden.results

Thanks,
Greg

**Comment by gjmzajac** [comment]
I just confirmed that converting the cov matrices as output by rvtests to the format that is output by raremetalworker also runs. Specifically, changing the header and columns does the trick.

/net/wonderland/home/gzajac/raremetal-develop/build/raremetal --summaryFiles /net/wonderland/home/gzajac/raremetal_tutorial/rvtests.summaryfiles --covFiles /net/wonderland/home/gzajac/raremetal_tutorial/rvtests.adj.covfiles --groupFile /net/wonderland/home/gzajac/raremetal_tutorial/group.file --burden --prefix /net/wonderland/home/gzajac/raremetal_tutorial/COMBINED.rvtests.adj_cov_f.QT1

**Comment by abought** [comment]
References: #13

**Comment by abought** [comment]
Thanks for the report, and the fix! 

Your changes have been merged, so I'll close this ticket. If problems recur, do feel welcome to reopen this ticket (or create a new one).
