### ISSUE TITLE
Fatal Error: No valid groups

### ISSUE THREAD

**Issue by jdarias93** [statgen/raremetal#16]
Dear raremetal team,

I am having trouble figuring out what the meaning/cause of this fatal error is:

> FATAL ERROR: 
> No valid groups. Unable to do gene-based test. Check if your group file is empty!

What is the group file? My apologies if this has been answered elsewhere.

Thank you in advance.

**Comment by abought** [comment]
Thanks for your question.

Forgive me if I'm starting with the basics, but  the group-based tests require some way of knowing what variants to include. A good source for information on this topic is our [wiki](https://genome.sph.umich.edu/wiki/Category:RAREMETAL), which covers the groupFile (and other alternate ways of specifying variants):
https://genome.sph.umich.edu/wiki/RAREMETAL_Documentation#From_a_Group_File

If you follow the guide in our [tutorial](https://genome.sph.umich.edu/wiki/Tutorial:_RAREMETAL), it includes a sample group file; the tutorial sample files are distributed alongside the source code in github:
https://github.com/statgen/raremetal/blob/master/tests/datasets/raremetal_tutorial/group.file

If you are sure that you have already defined groups, and are still getting this error, let us know and we can follow up.

**Comment by jdarias93** [comment]
Thank you for your help! Ok, great. I have two more (dumb) questions.

1) Are group files (and covariance files) required? According to the documentation, they aren't, but it doesn't explicitly say so.

2) How are group files generated? Through Raremetalworker/Rvtests? Or another way?

Thank you again for your help.

**Comment by abought** [comment]
The documentation could stand to be a bit better organized; here are some helpful sections:


>     1. Are group files (and covariance files) required? According to the documentation, they aren't, but it doesn't explicitly say so.

It depends on what kind of test you are trying to run.

"Grouping methods are only necessary when doing gene-based or group-based burden tests in meta-analysis." ([ref](https://genome.sph.umich.edu/wiki/RAREMETAL_Documentation#From_a_Group_File))

>     2. How are group files generated? Through Raremetalworker/Rvtests? Or another way?

There are several options exist for how to specify a group. ([ref](https://genome.sph.umich.edu/wiki/RAREMETAL_Command_Reference#Methods_to_Group_Rare_Variants)) Ultimately, the set of variants you choose to test depends on your hypothesis, and the group file format is a text-based file (see wiki docs and example file in the github link above).
 
For example, we are currently prototyping a web based tool to perform analysis on a particular pre-defined dataset, for some pre-defined masks relevant to our work. To help get a feel for what you might want to look at, the following link shows a sample of groups (masks) that we chose for this purpose. Ultimately, the decision on what or how to analyze is up to you.
https://statgen.github.io/locuszoom/examples/aggregation_tests.html
![Screen Shot 2019-07-10 at 5 21 39 PM](https://user-images.githubusercontent.com/2957073/61005956-33da8b00-a337-11e9-934a-29ffac515f9b.png)

**Comment by jdarias93** [comment]
@abought Thank you so much for your help.
