### ISSUE TITLE
Covariates are used only when --makeResiduals flag is on

### ISSUE THREAD

**Issue by achilleasNP** [statgen/raremetal#19]
Thank you for making raremetal available. I am using 
RAREMETALWORKER 4.15.1  and I am noticing this unexpected behavior.

Running the command below with the tutorial files:

```
raremetalworker  --ped example1.ped --dat example1.dat --vcf example1.vcf.gz --traitName QT1 --prefix withoutMakeResiduals
```

and looking at the header of the score file I see no covariates listed i.e.
##Covariates=
when I add --makeResiduals in the above command, that is:
```
raremetalworker  --ped example1.ped --dat example1.dat --vcf example1.vcf.gz --traitName QT1 --makeResiduals --prefix withMakeResiduals
```

 I see the covariates in the score file as:
##Covariates=AGE,AGE2,SEX
along with the covariate summaries.

Modifying the example1.dat file and setting all the variables to be traits produces the identical score result of my first command so covariates are not being used.

If you need any more details please let me know.

**Comment by welchr** [comment]
That's correct, with `--makeResiduals`, covariates are adjusted out of the phenotype to create residuals. The score tests are then calculated on those residuals. 

A few more examples can be found here: 

https://genome.sph.umich.edu/wiki/RAREMETALWORKER#General_Usage
https://genome.sph.umich.edu/wiki/RAREMETALWORKER_command_reference#Trait_Options

I'll add some clarifying text in the section about specifying covariates in the PED/DAT.

**Comment by achilleasNP** [comment]
Thanks for the quick reply!
