### ISSUE TITLE
Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz

### ISSUE THREAD

**Issue by tvanerp** [statgen/raremetal#39]
While running cget:

cget install -f requirements.txt

I get the following error:

Downloading http://zlib.net/zlib-1.2.11.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz
Failed to build package statgen/savvy

Seems like this package was updated to version 1.2.13 (http://zlib.net/) but I am not sure how to change the installation to download the updated version of zlib.

**Comment by jonathonl** [comment]
You can get around this by installing zlib with the corrected URL first.
```
cget install https://zlib.net/fossils/zlib-1.2.11.tar.gz
cget install -f requirements.txt
```

**Comment by tvanerp** [comment]
Thanks for the quick response.

It looks like zlib-1.2.11.tar.gz installs but "cget install -f requirements.txt" then still gives the same error.

cget install https://zlib.net/fossils/zlib-1.2.11.tar.gz
Downloading https://zlib.net/fossils/zlib-1.2.11.tar.gz
  [######################################################################]  100%
Extracting archive /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/build/tmp-38bc5e00e6b84fb1a698af20853e43b0/zlib-1.2.11.tar.gz ...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/build/tmp-38bc5e00e6b84fb1a698af20853e43b0/zlib-1.2.11/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CGET_CMAKE_DIR
    CGET_CMAKE_ORIGINAL_SOURCE_FILE


-- Build files have been written to: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/build/tmp-38bc5e00e6b84fb1a698af20853e43b0/build
[  5%] Building C object CMakeFiles/zlibstatic.dir/adler32.o
[  5%] Building C object CMakeFiles/zlibstatic.dir/compress.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/gzwrite.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/crc32.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/gzlib.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/deflate.o
[ 20%] Building C object CMakeFiles/zlibstatic.dir/gzread.o
[ 42%] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
[ 42%] Building C object CMakeFiles/zlib.dir/uncompr.o
[ 37%] Building C object CMakeFiles/zlib.dir/inffast.o
[ 52%] Building C object CMakeFiles/zlibstatic.dir/infback.o
[ 52%] Building C object CMakeFiles/zlib.dir/compress.o
[ 55%] Building C object CMakeFiles/zlibstatic.dir/inffast.o
[ 62%] Building C object CMakeFiles/zlib.dir/gzlib.o
[ 65%] Building C object CMakeFiles/zlib.dir/adler32.o
[ 75%] Building C object CMakeFiles/zlibstatic.dir/trees.o
[ 75%] Building C object CMakeFiles/zlib.dir/gzread.o
[ 75%] Building C object CMakeFiles/zlib.dir/infback.o
[ 62%] Building C object CMakeFiles/zlib.dir/inflate.o
[ 75%] Building C object CMakeFiles/zlibstatic.dir/inflate.o
[ 62%] Building C object CMakeFiles/zlib.dir/trees.o
[ 75%] Building C object CMakeFiles/zlib.dir/zutil.o
[ 65%] Building C object CMakeFiles/zlibstatic.dir/inftrees.o
[ 65%] Building C object CMakeFiles/zlib.dir/crc32.o
[ 65%] Building C object CMakeFiles/zlib.dir/deflate.o
[ 75%] Building C object CMakeFiles/zlibstatic.dir/zutil.o
[ 75%] Building C object CMakeFiles/zlib.dir/gzclose.o
[ 75%] Building C object CMakeFiles/zlib.dir/gzwrite.o
[ 75%] Building C object CMakeFiles/zlib.dir/inftrees.o
[ 77%] Linking C static library libz.a
[ 80%] Linking C shared library libz.so
[ 80%] Built target zlibstatic
[ 80%] Built target zlib
[ 90%] Building C object CMakeFiles/minigzip64.dir/test/minigzip.o
[ 90%] Building C object CMakeFiles/example64.dir/test/example.o
[ 90%] Building C object CMakeFiles/example.dir/test/example.o
[ 90%] Building C object CMakeFiles/minigzip.dir/test/minigzip.o
[ 92%] Linking C executable minigzip64
[ 95%] Linking C executable minigzip
[100%] Linking C executable example
[100%] Linking C executable example64
[100%] Built target minigzip
[100%] Built target minigzip64
[100%] Built target example64
[100%] Built target example
Consolidate compiler generated dependencies of target zlibstatic
Consolidate compiler generated dependencies of target zlib
[ 70%] Built target zlibstatic
[ 80%] Built target zlib
Consolidate compiler generated dependencies of target example
Consolidate compiler generated dependencies of target minigzip64
Consolidate compiler generated dependencies of target minigzip
Consolidate compiler generated dependencies of target example64
[100%] Built target minigzip64
[100%] Built target minigzip
[100%] Built target example64
[100%] Built target example
Install the project...
-- Install configuration: "Release"
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/lib/libz.so.1.2.11
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/lib/libz.so.1
-- Set runtime path of "/dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/lib/libz.so.1.2.11" to "/dfs4/som/tvanerp_col/bin/raremetal/cget/lib"
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/lib/libz.so
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/lib/libz.a
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/include/zconf.h
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/include/zlib.h
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/share/man/man3/zlib.3
-- Installing: /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/pkg/_url_emxpYi5uZXQvZm9zc2lscy96bGliLTEuMi4xMS50YXIuZ3o_/install/share/pkgconfig/zlib.pc
Successfully installed https://zlib.net/fossils/zlib-1.2.11.tar.gz
[tvanerp@login-i16:/dfs4/som/tvanerp_col/bin/raremetal] $cget install -f requirements.txt
Downloading https://github.com/statgen/savvy/archive/019a1ddaa9ec588f807f234f68787862f94ea057.tar.gz
  [######################################################################]  100%
Extracting archive /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/build/tmp-ede1ad783793420daaf21a08784b422e/019a1ddaa9ec588f807f234f68787862f94ea057.tar.gz ...
Downloading https://github.com/jonathonl/shrinkwrap/archive/develop.tar.gz
  [######################################################################]  100%
Extracting archive /dfs4/som/tvanerp_col/bin/raremetal/cget/cget/build/tmp-f6097eeeea6343baac865dadfdb80baf/develop.tar.gz ...
Downloading http://zlib.net/zlib-1.2.11.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz
Failed to build package statgen/savvy

Including cmake and cget versions in case useful to trouble shoot:

[tvanerp@login-i16:/dfs4/som/tvanerp_col/bin/raremetal] $cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[tvanerp@login-i16:/dfs4/som/tvanerp_col/bin/raremetal] $cget --version
cget, version 0.2.0

**Comment by tvanerp** [comment]
I started a clean install (new git clone).

This approach seems to work for me in terms of installing savvy, libStatGen, and Rmath:

cget install https://zlib.net/fossils/zlib-1.2.11.tar.gz
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/dfs4/som/tvanerp_col/bin/raremetal/cget/lib
cget install statgen/savvy
cget install statgen/libStatGen --cmake dep/libstatgen.cmake
cget install atks/Rmath --cmake dep/rmath.cmake

Though, then it appears  LIB_HTS and LIB_SAVVY may not be installed or defined?

mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cget/cget/cget.cmake -DBUILD_TESTS=1 ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- The Fortran compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped                                                                                
-- Detecting CXX compile features                                                                                                        
-- Detecting CXX compile features - done                                                                                                 
-- Detecting Fortran compiler ABI info                                                                                                   
-- Detecting Fortran compiler ABI info - done                                                                                            
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped                                                                       
-- Checking whether /usr/bin/gfortran supports Fortran 90                                                                                
-- Checking whether /usr/bin/gfortran supports Fortran 90 - yes                                                                          
-- Looking for pthread.h                                                                                                                 
-- Looking for pthread.h - found                                                                                                         
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD                                                                                               
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed                                                                                      
-- Looking for pthread_create in pthreads                                                                                                
-- Looking for pthread_create in pthreads - not found                                                                                    
-- Looking for pthread_create in pthread                                                                                                 
-- Looking for pthread_create in pthread - found                                                                                         
-- Found Threads: TRUE                                                                                                                   
-- Configuring done                                                                                                                      
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.                                             
Please set them or make sure they are set and tested correctly in the CMake files:                                                       
LIB_HTS                                                                                                                                  
    linked by target "libraremetal" in directory /dfs4/som/tvanerp_col/bin/raremetal                                                     
LIB_SAVVY                                                                                                                                
    linked by target "raremetalworker" in directory /dfs4/som/tvanerp_col/bin/raremetal                                                  
                                                                                                                                         
-- Generating done                                                                                                                       
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by jonathonl** [comment]
Sorry, what I meant to write was:
```
cget install zlib,https://zlib.net/fossils/zlib-1.2.11.tar.gz
cget install -f requirements.txt
```

You might need to `rm -r cget/` before running the two commands.

**Comment by tvanerp** [comment]
Super, thanks. Looks like that solved the install issue!
