### ISSUE TITLE
Problem using rvtest output for metanalyses

### ISSUE THREAD

**Issue by Carla1990** [statgen/raremetal#46]
When I run:
raremetal --summaryFiles path/Study1.singlevar.cov.txt.gz  path/Study2.Output.MetaScore.assoc.gz
		--covFiles path/Study1.singlevar.cov.txt.gz  path/Study2.Output.MetaScore.assoc.gz
                --groupFile refFlat_hg38.txt.gz \ 
                --SKAT --burden --MB --VT --longOutput --tabulateHits --hitsCutoff 1e-05 \ --prefix COMBINED.QT1

It gave me this type of error:
FATAL ERROR -
There are 1409629040 summary files and 1409722784 covariance files. 
Please check to make sure the same number of files are included in the list.

But I am using the outputs from the commands:

Study1:
raremetalworker  --ped example1.ped --dat example1.dat --vcf example1.vcf.gz --traitName QT1 \
                  --inverseNormal --makeResiduals --kinSave --kinGeno --prefix STUDY1 
Study2:
rvtests --inVcf input.vcf --pheno phenotype.ped --covar covar.txt --covar-name age,sex,bmi,PC1,PC2,PC3PC4,PC4,PC5 --inverseNormal --useResidualAsPhenotype  --meta score,cov --out output 

Do you have any idea why?
Thank you so much

**Comment by welchr** [comment]
`--summaryFiles` and `--covFiles` take in plain text files, each of which has a list of the score statistic (`--summaryFiles`) or covariance matrix (`--covFiles`) files to use for analysis. 

See also: https://genome.sph.umich.edu/wiki/RAREMETAL_Documentation#List_of_Studies
