### ISSUE TITLE
Object files in a git tree

### ISSUE THREAD

**Issue by ersereik** [statgen/raremetal#9]
Hi,

Why are objects committed to git, I banged my head against the wall quite long time until I realized that make clean does not clean all objects. I got linking errors like "undefined reference to `__fdelt_chk'"

Problematic ones are here:
https://github.com/statgen/raremetal/tree/master/libStatGen/samtools/obj

**Comment by abought** [comment]
Indeed! Would you be willing to try this on the `develop` branch, and report back on whether your problem persists? 

It simplifies the build process substantially (in addition to some bug fixes):
https://github.com/statgen/raremetal/tree/develop

**Comment by abought** [comment]
Version 4.15.0 has been released, which removes the object files and includes the substantial build changes mentioned previously. Since we haven't heard back with further issues, I'll close this ticket.
